FROM eclipse-temurin:21-jre-alpine

# Copie le .class dans le conteneur
COPY Main.class /app/Main.class

# Définit le dossier de travail
WORKDIR /app

# Commande pour exécuter le programme
CMD ["java", "Main"]
