- name: Run backend API container
  docker_container:
    name: backend-api
    image: marionbln/tp-postgres-simpleapi:latest 
    pull: yes   # ← Image DockerHub
    state: started
    restart_policy: on-failure
    networks:
      - name: app-network
      - name: app-network2
    env:
      DB_URL: jdbc:postgresql://postgres:5432/mydb
      DB_USERNAME: usr
      DB_PASSWORD: pwd
  