- name: Run backend API container
  docker_container:
    name: backend-api
    image: victoireepf/tp-simpleapi:latest
    pull: yes   # ← Image DockerHub
    state: started
    restart_policy: on-failure 
    networks:
      - name: app-network
      - name: app-network2

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: pwd 
  