services:
  backend:
    build:
      context: ./simpleapi
    container_name: backend-api
    networks:
      - app-network
      - app-network2
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    restart: on-failure  

  database:
    build:
      context: ./database
    container_name: postgres
    networks:
      - app-network
    volumes:
      - TP1_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  httpd:
    build:
      context: ./http-server
    container_name: apache-server
    ports:
      - "80:80"
    networks:
      - app-network2
    depends_on:
      - backend
    restart: "no"

networks:
  app-network:
  app-network2:

volumes:
  TP1_postgres_data:
