services:
  backend:
    build:
      context: ./simpleapi #constrcution de l'image à l'aide du dossier backend 
    container_name: backend-api #nom du conteneur au lancement 
    networks: #je met les deux réseaux avec lesquels il communique 
      - app-network
      - app-network2 
    depends_on:
      - database #on attend que le conteneur de la base de données soit lancé avant de lancer le conteneur backend
    environment: #les variables se trouvent dans un fichier .env pour augmenter la sécurité
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: 
      on-failure:3

  database:
    build:
      context: ./database
    container_name: postgres
    networks:
      - app-network
    volumes:
      - TP1_postgres_data:/var/lib/postgresql/data #permet la persistance des données
    restart: 
      unless-stopped

  httpd:
    build:
      context: ./http-server
    container_name: apache-server
    ports:
      - "80:80"
    networks:
      - app-network2
    depends_on:
      - backend #on attend le lancement du backend avant le serveur http 
    restart: 
      no 

networks:
  app-network:
  app-network2:

volumes:
  TP1_postgres_data:
