- name: Run Apache HTTP server
  docker_container:
    name: http-server
    image: victoireepf/tp-httpd:latest
    state: started
    ports:
      - "80:80"
    networks:
      - name: app-network2
      - name : app-network3

