name: CD - Docker publish

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["CI devops 2025"] 
    types:
      - completed  

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend (simpleapi)
        uses: docker/build-push-action@v6
        with:
          context: ./Jour-1/simpleapi
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-simpleapi:latest
          push: true

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./Jour-1/database
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-database:latest
          push: true

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./Jour-1/http-server
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-httpd:latest
          push: true
          
