name: CD - Docker publish

on:
  workflow_run:
    workflows: ["CI - Test backend"]  
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend (simpleapi)
        uses: docker/build-push-action@v6
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./Jour-1/simpleapi
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKER_USERNAME}}/tp-postgres-simpleapi:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./Jour-1/backend
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKER_USERNAME}}/tp-postgres-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./Jour-1/backend
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKER_USERNAME}}/tp-postgres-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}

